version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
  get_notes:
    container_name: get_notes
    build:
      context: ./get_notes
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
